### PR TITLE
Pulsar Log4j2 Appender: allow configuration of the client

### LINKED ISSUE #15: [log4j2-appender] Multiple application instances cannot produce to same topic
**Describe the bug**

Multiple application instances cannot produce to same topic when using the Pulsar Log4j2 appender.
This is due to the fixed producer name set in the log4j2 appender code.

https://github.com/apache/pulsar-adapters/blob/c0bb58d02404f02fd34eaf1c726aa168d90d6e8b/pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarManager.java#L116

**To Reproduce**

follow instructions in https://github.com/lhotari/pulsar-log4j2-appender-demo#running-multiple-applications 

**Expected behavior**

Multiple applications should be able to produce log events to the same topic.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #15, #16

### Motivation

When Pulsar security is enabled, the current implementation is unusable. This PR also covers the feature request #16 to allow configuring most client and producer configuration properties.
The issue #15 makes the Pulsar Log4j2 Appender unusable in many use cases. This PR fixes the issue by removing the hard coded producer name.
The current build for Pulsar Log4j2 Appender is broken. This PR fixes the build by properly configuring Log4j2 plugin annotation processor for the maven build. There were broken tests which were unnecessary and testing Log4j2 internals instead of the appender. Those tests have been removed

### Modifications

- add support for configuring Pulsar client and producer configuration properties (#16)
- fix maven build (Log4j2 plugin annotation processor)
- remove broken tests which were unnecessary
- remove the hard coded producer name which prevented using the appender in many use cases (#15)

### CODE REVIEW

File: pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java [hunk 1]
```diff
@@ -186,7 +185,7 @@ public void start() {
         try {
             manager.startup();
         } catch (Exception e) {
-            // fail to start the manager
+            LOGGER.error("Failed to start pulsar manager", e);
```
Comment (eolivelli) [inline pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java:188]: should we throw a RuntimeException ?

if you configure the logger to write to Pulsar and we are not able to setup the Pulsar client we are going to lose data

File: pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/AbstractPulsarAppenderTest.java [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+
+        PulsarManager.PULSAR_CLIENT_BUILDER = () -> clientBuilder;
+
+        ctx = Configurator.initialize(
+                "PulsarAppenderTest",
+                getClass().getClassLoader(),
+                getClass().getClassLoader().getResource(resourceName).toURI());
+    }
+
+    protected LogEvent deserializeLogEvent(final byte[] data) throws IOException, ClassNotFoundException {
```
Comment (eolivelli) [inline pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/AbstractPulsarAppenderTest.java:161]: a good follow up of this patch is to add support for encoding log events to JSON.

Java Serialization is unsecure, and also if we support JSON it would be super easy to integrate with the ElasticSearch or the Cassandra Sink

File: pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java:188]: see here https://github.com/apache/pulsar-adapters/pull/17/files#diff-edfe43967b455a71721fe0569016ff77ad3118a25c3616a342500b2f837bd9b9L130

File: pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/AbstractPulsarAppenderTest.java (hunk 2 above)
Comment (lhotari) [reply pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/AbstractPulsarAppenderTest.java:161]: JSON serialization works out of the box when Jackson is on the classpath. I have experimented with that in https://github.com/lhotari/pulsar-log4j2-appender-demo#k8s-demo .

File: pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java (hunk 1 above)
Comment (lhotari) [reply pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java:188]: I didn't change the external behavior of the previous solution. I simply removed the catch in the location which you linked to and moved the logging to the upper level (here) since it reduces the confusion about swallowing the exception and not logging it.

It would be a breaking change to throw the exception as a RuntimeException. For example, if Pulsar is unavailable the application wouldn't be able to start. This might not be the desired behavior. I think changing the behavior would require a new configuration option and that would be a separate PR.

File: pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/AbstractPulsarAppenderTest.java (hunk 2 above)
Comment (eolivelli) [reply pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/AbstractPulsarAppenderTest.java:161]: great

File: pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarAppender.java:188]: makes sense

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]
